# Generated by Django 5.0.6 on 2024-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Extra',
        ),
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(to='example.movie'),
        ),
    ]
