# Generated by Django 5.0.6 on 2024-06-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_character_movie_delete_extra_character_movies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataExample',
        ),
    ]
